using EmployeeManagement.Application.Abstractions.Persistence;
using EmployeeManagement.Domain.Common;
using EmployeeManagement.Domain.Models;
using EmployeeManagement.Infrastructure.Context;
using EmployeeManagement.Infrastructure.Entity;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Infrastructure.Repositories.Employees;

/// <summary>
/// EF Core implementation of <see cref="IEmployeeRepository"/> over <c>dbo.tblEmployee</c>.
/// </summary>
internal sealed class EmployeeRepository(EmployeeDbContext context) : IEmployeeRepository
{
    /// <inheritdoc />
    public async Task<PagedResult<Employee>> GetPagedAsync(
        int pageNumber,
        int pageSize,
        string? search,
        CancellationToken cancellationToken)
    {
        var query = context.TblEmployees.AsNoTracking();

        if (!string.IsNullOrWhiteSpace(search))
        {
            var term = search.Trim();

            query = query.Where(employee =>
                EF.Functions.Like(employee.Name, $"%{term}%")
                || EF.Functions.Like(employee.Mobile, $"%{term}%")
                || EF.Functions.Like(employee.Email, $"%{term}%"));
        }

        // The count is taken before paging so that the caller can navigate the whole result set.
        var totalCount = await query.CountAsync(cancellationToken);

        var employees = await query
            .OrderBy(employee => employee.EmpId)
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        return new PagedResult<Employee>(
            employees.Select(ToModel).ToList(),
            pageNumber,
            pageSize,
            totalCount);
    }

    /// <inheritdoc />
    public async Task<Employee?> GetByIdAsync(int id, CancellationToken cancellationToken)
    {
        var employee = await context.TblEmployees
            .AsNoTracking()
            .FirstOrDefaultAsync(record => record.EmpId == id, cancellationToken);

        return employee is null ? null : ToModel(employee);
    }

    /// <inheritdoc />
    public async Task<int> AddAsync(Employee employee, CancellationToken cancellationToken)
    {
        var entity = new TblEmployee
        {
            Name = employee.Name,
            Mobile = employee.Mobile,
            Email = employee.Email,
            IsActive = employee.IsActive
        };

        context.TblEmployees.Add(entity);

        await context.SaveChangesAsync(cancellationToken);

        // EmpId is generated by the database and is populated after SaveChanges.
        return entity.EmpId;
    }

    /// <inheritdoc />
    public async Task<bool> UpdateAsync(Employee employee, CancellationToken cancellationToken)
    {
        var entity = await context.TblEmployees
            .FirstOrDefaultAsync(record => record.EmpId == employee.EmpId, cancellationToken);

        if (entity is null)
        {
            return false;
        }

        entity.Name = employee.Name;
        entity.Mobile = employee.Mobile;
        entity.Email = employee.Email;
        entity.IsActive = employee.IsActive;

        await context.SaveChangesAsync(cancellationToken);

        return true;
    }

    /// <inheritdoc />
    public async Task<bool> DeleteAsync(int id, CancellationToken cancellationToken)
    {
        var entity = await context.TblEmployees
            .FirstOrDefaultAsync(record => record.EmpId == id, cancellationToken);

        if (entity is null)
        {
            return false;
        }

        context.TblEmployees.Remove(entity);

        await context.SaveChangesAsync(cancellationToken);

        return true;
    }

    private static Employee ToModel(TblEmployee entity) => new()
    {
        EmpId = entity.EmpId,
        Name = entity.Name,
        Mobile = entity.Mobile,
        Email = entity.Email,
        IsActive = entity.IsActive
    };
}
