using Asp.Versioning.ApiExplorer;

namespace EmployeeManagement.Api.Documentation;

/// <summary>
/// Serves the Swagger UI over the OpenAPI documents generated by <c>Microsoft.AspNetCore.OpenApi</c>
/// and versioned by <c>Asp.Versioning.OpenApi</c>.
/// </summary>
/// <remarks>
/// Development only: the documents and the UI are mapped inside the <c>IsDevelopment</c> branch of
/// <c>Program.cs</c>, so no documentation surface exists in other environments.
/// </remarks>
public static class ApiDocumentationExtensions
{
    /// <summary>
    /// Absolute path prefix the documentation UI is served from.
    /// </summary>
    /// <remarks>
    /// The prefix is also handed to the security headers middleware, which is the only reason these
    /// paths receive a relaxed content security policy: Swagger UI is a browser application, and the
    /// strict policy applied to JSON responses (<c>default-src 'none'</c>) would block it.
    /// </remarks>
    public const string PathPrefix = "/swagger";

    /// <summary>
    /// Maps the Swagger UI, with one document selector entry per API version.
    /// </summary>
    /// <param name="endpoints">The endpoint route builder.</param>
    /// <returns>
    /// An endpoint convention builder, so the caller can keep the documentation anonymous in the
    /// same way as the other development only endpoints.
    /// </returns>
    public static IEndpointConventionBuilder MapApiDocumentation(this IEndpointRouteBuilder endpoints)
    {
        ArgumentNullException.ThrowIfNull(endpoints);

        var descriptions = endpoints.ServiceProvider
            .GetRequiredService<IApiVersionDescriptionProvider>()
            .ApiVersionDescriptions;

        return endpoints.MapSwaggerUI(PathPrefix.TrimStart('/'), options =>
        {
            options.DocumentTitle = "Employee Management API";
            options.EnableDeepLinking();

            // Keeps the access token in the browser between page reloads, so a developer does not
            // have to sign in again after every rebuild.
            options.EnablePersistAuthorization();

            foreach (var description in descriptions)
            {
                // The version group name is the document name produced by the versioning conventions
                // ("v1" describes /openapi/v1.json), so adding an API version adds a document and a
                // selector entry without any change here.
                options.SwaggerEndpoint(
                    $"/openapi/{description.GroupName}.json",
                    $"Employee Management API {description.GroupName}");
            }
        });
    }
}

