/**
 * Configuration applied to production builds (`ng build`, `ng serve --configuration production`).
 *
 * `apiBaseUrl` is prefixed to every path generated by `EmployeesClient`
 * (see `src/app/core/services/api-client.ts`).
 *
 * - Leave it empty when the UI and the API share an origin. This is the case when the built
 *   application is published behind a reverse proxy (Nginx, IIS, YARP, ...) that forwards
 *   `/api/**` to the ASP.NET Core API.
 * - Set an absolute origin (trailing slash included) when the API lives on another host, for
 *   example `https://api.example.com/`. The API must then allow the UI origin through CORS.
 */
export const environment = {
  production: true,
  apiBaseUrl: '',
};
